-- AGENDA definition

-- Drop table

-- DROP TABLE AGENDA;

CREATE TABLE AGENDA (
	ID INTEGER NOT NULL,
	IDPROFISSIONAL INTEGER NOT NULL,
	DIA DATE NOT NULL,
	HORARIO TIME,
	IDCLIENTE TIME,
	CONSTRAINT PK_AGENDA PRIMARY KEY (ID)
);


-- CLIENTE definition

-- Drop table

-- DROP TABLE CLIENTE;

CREATE TABLE CLIENTE (
	ID INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50) NOT NULL,
	DATANASCIMENTO DATE NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);


-- DATAETURNOS definition

-- Drop table

-- DROP TABLE DATAETURNOS;

CREATE TABLE DATAETURNOS (
	ID INTEGER NOT NULL,
	IDPROFISSIONAL INTEGER NOT NULL,
	TURNO CHAR(5) NOT NULL,
	DIA DATE NOT NULL,
	CONSTRAINT PK_DATAETURNOS PRIMARY KEY (ID,IDPROFISSIONAL,TURNO,DIA)
);


-- HORARIOS definition

-- Drop table

-- DROP TABLE HORARIOS;

CREATE TABLE HORARIOS (
	ID INTEGER NOT NULL,
	IDDATAETURNOS INTEGER NOT NULL,
	HORARIO TIME NOT NULL,
	IDCLIENTE INTEGER,
	CONSTRAINT PK_HORARIOS PRIMARY KEY (ID,IDDATAETURNOS,HORARIO)
);


-- PROFISSIONAIS definition

-- Drop table

-- DROP TABLE PROFISSIONAIS;

CREATE TABLE PROFISSIONAIS (
	ID INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50) NOT NULL,
	HORARIO_MIN_MANHA TIME,
	HORARIO_MAX_MANHA TIME,
	HORAUNITARIA TIME,
	HORARIO_MIN_TARDE TIME,
	HORARIO_MAX_TARDE TIME,
	CONSTRAINT PK_PROFISSIONAIS PRIMARY KEY (ID),
	CONSTRAINT UK_NOME UNIQUE (NOME)
);
CREATE UNIQUE INDEX IX_NOME ON PROFISSIONAIS (NOME);