delete FROM horarios

DELETE FROM agenda

delete FROM DATAETURNOS 

SELECT p.nome, d.TURNO , d.DIA , h.HORARIO  FROM DATAETURNOS d INNER JOIN
horarios h ON d.ID = h.IDDATAETURNOS
INNER JOIN profissionais p ON d.IDPROFISSIONAL = p.id;

-- HORARIOS definition

-- Drop table

DROP TABLE HORARIOS;

CREATE TABLE HORARIOS (
	ID INTEGER NOT NULL,
	IDDATAETURNOS INTEGER NOT NULL,
	HORARIO TIME NOT NULL,
	IDCLIENTE INTEGER,
	CONSTRAINT PK_HORARIOS PRIMARY KEY (ID,IDDATAETURNOS,HORARIO)
);